### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [KaidanIM/Kaidan#213]
It is possible to have a XEPs and RFCs support page with VERSION?
https://github.com/KaidanIM/Kaidan/wiki/Supported-XMPP-Extension-Protocols-(XEPs)

Examples:
- https://metronome.im/supported-xeps-list
- https://trac.gajim.org/wiki/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by JBBgameich** [comment]
We already have such a list located on the [wiki](https://github.com/KaidanIM/Kaidan/wiki/Supported-XMPP-Extension-Protocols-(XEPs)). However I can't guarantee that it's really up to date.

**Comment by Neustradamus** [comment]
Good first step, now there is only VERSION missing :)

**Comment by LNJ2** [comment]
Btw, hello and welcome! :smiley: 
I'll see which exact versions gloox supports and update it in the Wiki. I think a link to the supported XEPs in the README would also be nice.

**Comment by Neustradamus** [comment]
Thanks it is better :)
Hope an update of the XEPs ;)

**Comment by LNJ2** [comment]
Thats probably out of scope of kaidan, but I'll mail the author of gloox (our XMPP library)

**Comment by Neustradamus** [comment]
- https://github.com/KaidanIM/gloox-git
- https://github.com/KaidanIM/gloox-packaging

**Comment by LNJ2** [comment]
@Neustradamus What about these repos?

**Comment by LNJ2** [comment]
The development isn't really dead, the author of the library still accepts patches & new features. These repos are just existing to make building easier for us (git instead of svn) and the packaging repo is only existing because the debian maintainers have not released the latest version, which we depend on.

I don't see a good reason why we should fork the library and I personally also don't want to maintain such a library in the long run.
