### ISSUE TITLE
Kaidan UI design guidelines

### ISSUE THREAD

**Issue by JBBgameich** [KaidanIM/Kaidan#32]
I think it's time to agree on the design.
I will list a few things to decide on:

- Which UI frameworks do we want to use?
    * Silica (Sailfish OS) 
    * Kirigami (Desktop, Android, Plasma Mobile, we would need to test building for sailfish OS, maybe without mer SDK)
    * Use both, Silica for Sailfish and Kirigami for all the other platforms

Breeze icon theme on all platforms or not (does SailfishOS has it's own?)

**Comment by LNJ2** [comment]
If someone here wants to __*ONLY*__ use Silica, this is the wrong project. So option one, clearly not.

I think we should use both until we get a good looking style with kirigami(2) + QuickControls(2) on SFOS.

Icons can be different on SFOS, but I think generally breeze icons or completely new icons.


And I would like to make one rule:
* If someone makes a PR, she/he (or someone else who wants to help) has to add everything for all platforms, so with Kirigami *and* Silica/SFOS variant. So that no platform disadvantaged.

**Comment by geobra** [comment]
As I told before, for me Sailfish is my main platform. Later maybe Plasma Mobile, if it gets stable and usable. Sailfish is currently based on Qt 5.2. They work on Qt 5.6, I think because it's a TLS Release. Because of this, I doubt that we can use the same UI on all platforms. So everyone is more then welcome to provide a good and nice UI using kirigami for the other platforms. To be honest, I am waiting to see at least a mock up since project start. Personally, I will not work on a kirigami UI.

**Comment by LNJ2** [comment]
@geobra I know here is not much happening and I also would like to really *start*. I just had not much time in the last weeks. I hope that will be better in the next time (at the very latest, I will find time at christmas). And one thing why we (I and JBB) have not started to add kirigami, is the build system... and the not existing dependency handling by qmake. (e.g. -lSwiften_Boost will only work if you have the older boost version provided by swift, and not with the system's version, what was my problem)

And you won't have to do anything related to kirigami, if we do the kirigami part.
But nevertheless I would like to add the rule I mentioned above. (so someone has to add the kirigami part to all of your PRs and you the silica side to our PRs with kirigami) Would that be ok? @geobra @MRZA-MRZA
